# BuildDav1d.cmake — fetch dav1d's pinned source and compile it C-only (no meson,
# no nasm), the same way dasImgui FetchContent's + compiles imgui. Keeps
# `daspkg install` a plain cmake build: the consumer needs only git + cmake + a C
# compiler (which daspkg already requires), never meson/ninja/nasm.
#
# The asm block of dav1d's build is skipped entirely (HAVE_ASM=0), so this is the
# 25 core sources + 13 bitdepth-templated sources compiled twice (8/16 bpc). An
# optimized prebuilt-lib path via daspkg is a planned follow-up.

include(FetchContent)
include(CheckSymbolExists)
include(CheckIncludeFile)
include(CheckCSourceCompiles)

set(DAV1D_VERSION 1.5.3)

FetchContent_Declare(dav1d_src
    URL https://github.com/videolan/dav1d/archive/refs/tags/${DAV1D_VERSION}.tar.gz
    SOURCE_DIR ${DAS_VIDEO_DIR}/vendor/dav1d)
FetchContent_MakeAvailable(dav1d_src)
set(DAV1D ${DAS_VIDEO_DIR}/vendor/dav1d)

# ---- config.h: feature-detect the platform-varying defines ----
check_symbol_exists(posix_memalign "stdlib.h"  DAV1D_HAVE_POSIX_MEMALIGN)
check_symbol_exists(memalign       "malloc.h"  DAV1D_HAVE_MEMALIGN)
check_symbol_exists(aligned_alloc  "stdlib.h"  DAV1D_HAVE_ALIGNED_ALLOC)
check_symbol_exists(clock_gettime  "time.h"    DAV1D_HAVE_CLOCK_GETTIME)
check_symbol_exists(dlsym          "dlfcn.h"   DAV1D_HAVE_DLSYM)
check_include_file(unistd.h        DAV1D_HAVE_UNISTD_H)
check_include_file(io.h            DAV1D_HAVE_IO_H)
check_include_file(sys/types.h     DAV1D_HAVE_SYS_TYPES_H)
check_c_source_compiles("int main(void){int x=_Generic(0,default:0);return x;}" DAV1D_HAVE_C11_GENERIC)

# normalize the check results to 0/1 for the @VAR@ substitution
foreach(v POSIX_MEMALIGN MEMALIGN ALIGNED_ALLOC CLOCK_GETTIME DLSYM
          UNISTD_H IO_H SYS_TYPES_H C11_GENERIC)
    if(DAV1D_HAVE_${v})
        set(DAV1D_HAVE_${v} 1)
    else()
        set(DAV1D_HAVE_${v} 0)
    endif()
endforeach()

# thread niceties (affinity/naming) — 0 everywhere is safe (just drops the nicety)
set(DAV1D_HAVE_PTHREAD_GETAFFINITY_NP 0)
set(DAV1D_HAVE_PTHREAD_SETAFFINITY_NP 0)
set(DAV1D_HAVE_PTHREAD_SETNAME_NP 0)

# endianness
if(CMAKE_C_BYTE_ORDER STREQUAL "BIG_ENDIAN")
    set(DAV1D_ENDIANNESS_BIG 1)
else()
    set(DAV1D_ENDIANNESS_BIG 0)
endif()

# arch
set(DAV1D_ARCH_AARCH64 0)
set(DAV1D_ARCH_ARM 0)
set(DAV1D_ARCH_X86 0)
set(DAV1D_ARCH_X86_64 0)
set(DAV1D_ARCH_X86_32 0)
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _dav1d_proc)
if(_dav1d_proc MATCHES "aarch64|arm64")
    set(DAV1D_ARCH_AARCH64 1)
elseif(_dav1d_proc MATCHES "^arm")
    set(DAV1D_ARCH_ARM 1)
elseif(_dav1d_proc MATCHES "x86_64|amd64|x64")
    set(DAV1D_ARCH_X86 1)
    set(DAV1D_ARCH_X86_64 1)
elseif(_dav1d_proc MATCHES "i[3-6]86|x86")
    set(DAV1D_ARCH_X86 1)
    set(DAV1D_ARCH_X86_32 1)
endif()

# windows-only config block
if(WIN32)
    set(DAV1D_WIN32_CONFIG "#define UNICODE 1\n#define _UNICODE 1\n#define _WIN32_WINNT 0x0601\n#define _CRT_DECLARE_NONSTDC_NAMES 1\n#define _FILE_OFFSET_BITS 64")
    if(MINGW)
        string(APPEND DAV1D_WIN32_CONFIG "\n#define __USE_MINGW_ANSI_STDIO 1")
    endif()
else()
    set(DAV1D_WIN32_CONFIG "")
endif()

set(_dav1d_gen ${CMAKE_CURRENT_BINARY_DIR}/dav1d_gen)
configure_file(${CMAKE_CURRENT_LIST_DIR}/dav1d_config.h.in ${_dav1d_gen}/config.h @ONLY)
file(WRITE ${_dav1d_gen}/vcs_version.h "/* generated by dasVideo CMake */\n#define DAV1D_VERSION \"${DAV1D_VERSION}\"\n")

# ---- source lists (mirrors src/meson.build, asm block omitted) ----
set(_dav1d_core
    cdf.c cpu.c ctx.c data.c decode.c dequant_tables.c getbits.c intra_edge.c
    itx_1d.c lf_mask.c lib.c log.c mem.c msac.c obu.c pal.c picture.c qm.c ref.c
    refmvs.c scan.c tables.c thread_task.c warpmv.c wedge.c)
set(_dav1d_tmpl
    cdef_apply_tmpl.c cdef_tmpl.c fg_apply_tmpl.c filmgrain_tmpl.c
    ipred_prepare_tmpl.c ipred_tmpl.c itx_tmpl.c lf_apply_tmpl.c loopfilter_tmpl.c
    looprestoration_tmpl.c lr_apply_tmpl.c mc_tmpl.c recon_tmpl.c)
list(TRANSFORM _dav1d_core PREPEND ${DAV1D}/src/)
list(TRANSFORM _dav1d_tmpl PREPEND ${DAV1D}/src/)
if(WIN32)
    list(APPEND _dav1d_core ${DAV1D}/src/win32/thread.c)
endif()

set(_dav1d_inc ${_dav1d_gen} ${DAV1D} ${DAV1D}/include ${DAV1D}/include/dav1d ${DAV1D}/src)
if(MSVC)
    list(APPEND _dav1d_inc ${DAV1D}/include/compat/msvc)
endif()

# bitdepth-templated sources: one object lib per bitdepth (BITDEPTH=8 / =16)
add_library(dav1d_bd8  OBJECT ${_dav1d_tmpl})
add_library(dav1d_bd16 OBJECT ${_dav1d_tmpl})
target_compile_definitions(dav1d_bd8  PRIVATE BITDEPTH=8)
target_compile_definitions(dav1d_bd16 PRIVATE BITDEPTH=16)

# the decoder static lib: core + both bitdepth object sets
add_library(dav1d_dec STATIC ${_dav1d_core}
    $<TARGET_OBJECTS:dav1d_bd8> $<TARGET_OBJECTS:dav1d_bd16>)

foreach(_t dav1d_dec dav1d_bd8 dav1d_bd16)
    target_include_directories(${_t} PRIVATE ${_dav1d_inc})
    set_target_properties(${_t} PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON
        POSITION_INDEPENDENT_CODE ON)
endforeach()

find_package(Threads REQUIRED)
target_link_libraries(dav1d_dec PUBLIC Threads::Threads)
# the module includes <dav1d/dav1d.h> from here
target_include_directories(dav1d_dec PUBLIC ${DAV1D}/include)

message(WARNING "dasVideo: dav1d ${DAV1D_VERSION} is built C-only (no SIMD asm) — "
    "portable and dependency-free, but slower to decode than an asm build. "
    "Optimized prebuilt libraries via daspkg are a planned follow-up.")
